"""Casestore port — defines the contract for case persistence."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from src.domain.case import (
    Artifact,
    ArtifactStream,
    Case,
    Comment,
    RelatedEvent,
)


@runtime_checkable
class Casestore(Protocol):
    """Protocol that any case-storing adapter must satisfy."""

    async def create(self, case: Case) -> Case: ...

    async def update(self, case: Case) -> Case: ...

    async def get_case(self, case_id: str) -> Case | None: ...

    async def get_case_history(self, case_id: str) -> list[Any]: ...

    async def create_comment(self, comment: Comment) -> Comment: ...

    async def get_comment(self, comment_id: str) -> Comment | None: ...

    async def get_comments(self, case_id: str) -> list[Comment]: ...

    async def update_comment(self, comment: Comment) -> Comment: ...

    async def delete_comment(self, comment_id: str) -> None: ...

    async def create_related_events(
        self, events: list[RelatedEvent],
    ) -> tuple[int, dict[str, str], None | str]: ...

    async def get_related_event(self, event_id: str) -> RelatedEvent | None: ...

    async def get_related_events(self, case_id: str) -> list[RelatedEvent]: ...

    async def delete_related_event(self, event_id: str) -> None: ...

    async def create_artifact(self, artifact: Artifact) -> Artifact: ...

    async def get_artifact(self, artifact_id: str) -> Artifact | None: ...

    async def get_artifacts(
        self, case_id: str, group_type: str, group_id: str,
    ) -> list[Artifact]: ...

    async def delete_artifact(self, artifact_id: str) -> None: ...

    async def update_artifact(self, artifact: Artifact) -> Artifact: ...

    async def create_artifact_stream(self, stream: ArtifactStream) -> str: ...

    async def get_artifact_stream(self, stream_id: str) -> ArtifactStream | None: ...

    async def delete_artifact_stream(self, stream_id: str) -> None: ...
