"""Detection ports -- Detectionstore and DetectionEngine protocols."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from src.domain.detection import Detection, DetectionComment


@runtime_checkable
class Detectionstore(Protocol):
    """Protocol that any detection storage adapter must satisfy."""

    async def create_detection(self, detection: Detection) -> Detection: ...
    async def get_detection(self, detection_id: str) -> Detection: ...
    async def get_detection_by_public_id(self, public_id: str) -> Detection | None: ...
    async def update_detection(self, detection: Detection) -> Detection: ...
    async def delete_detection(self, detection_id: str) -> Detection: ...
    async def get_detection_history(self, detection_id: str) -> list[Any]: ...

    async def create_comment(self, comment: DetectionComment) -> DetectionComment: ...
    async def get_comment(self, comment_id: str) -> DetectionComment: ...
    async def get_comments(self, detection_id: str) -> list[DetectionComment]: ...
    async def update_comment(self, comment: DetectionComment) -> DetectionComment: ...
    async def delete_comment(self, comment_id: str) -> None: ...


@runtime_checkable
class DetectionEngine(Protocol):
    """Protocol that any detection engine adapter must satisfy."""

    async def validate_rule(self, rule: str) -> str: ...
    async def extract_details(self, detection: Detection) -> None: ...
    async def apply_filters(self, detection: Detection) -> bool: ...
    async def sync_local_detections(self, detections: list[Detection]) -> dict[str, str]: ...
    async def convert_rule(self, detection: Detection) -> str: ...
    async def duplicate_detection(self, detection: Detection) -> Detection: ...
    async def generate_unused_public_id(self) -> str: ...
    async def merge_auxiliary_data(self, detection: Detection) -> None: ...
    async def interrupt_sync(self, force_full: bool, notify: bool) -> None: ...
